# Generated by Django 2.1.5 on 2019-01-29 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=30)),
                ('b_owner_name', models.CharField(max_length=30)),
                ('b_contact', models.CharField(max_length=12)),
                ('b_addr', models.TextField()),
                ('b_pan_no', models.CharField(max_length=10)),
                ('b_est_date', models.DateField()),
                ('b_type', models.CharField(max_length=20)),
                ('b_applied_date', models.DateTimeField(default=datetime.datetime(2019, 1, 29, 15, 13, 42, 778833))),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_email', models.EmailField(max_length=254)),
                ('ap_mob', models.CharField(max_length=12)),
                ('ap_ip_addr', models.GenericIPAddressField()),
                ('ap_pass', models.CharField(max_length=14)),
                ('ap_date', models.DateTimeField(default=datetime.datetime(2019, 1, 29, 15, 13, 42, 777833))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='ap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Signup'),
        ),
    ]
