# Generated by Django 2.1.5 on 2019-01-28 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_email', models.EmailField(max_length=254)),
                ('ap_mob', models.CharField(max_length=12)),
                ('ap_ip_addr', models.GenericIPAddressField()),
                ('ap_pass', models.CharField(max_length=14)),
                ('ap_date', models.DateTimeField(default=datetime.datetime(2019, 1, 28, 16, 7, 1, 448553))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
