# Generated by Django 2.1.5 on 2019-01-28 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='ap_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 16, 22, 42, 364370)),
        ),
    ]
